# Generated by Django 4.1.5 on 2023-01-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("men", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menmodel",
            name="img",
            field=models.ImageField(default=None, upload_to="static/media/"),
        ),
        migrations.AlterField(
            model_name="menmodel",
            name="age",
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="menmodel",
            name="city",
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name="menmodel",
            name="name",
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name="menmodel",
            name="salary",
            field=models.IntegerField(default=None),
        ),
    ]
